### ISSUE TITLE
C3.js instead of Morris

### ISSUE THREAD

**Issue by ehartford** [kumailht/flakes#24]
Morris' donut charts are not useful because you have to hover your mouse over each slice to see the data.
Most business use cases are pie charts (like it or not) and we want the percentage / value displayed immediately with no user interaction required.
Therefore I recommend using C3.js instead of Morris for the charts.
http://c3js.org/samples/chart_pie.html

**Comment by ls42** [comment]
@kumailht You should close this issue :smiley:
