### ISSUE TITLE
Classes for use in form validation

### ISSUE THREAD

**Issue by ls42** [kumailht/flakes#34]
I think it would be useful to have some clean CSS classes that can be used in form validation. Style changes like text color, background color...

It is easy to put this in custom CSS, but I think it should be in the basic framework itself. Like bootstraps `has-error`, `has-warning` and so on.

**Comment by kumailht** [comment]
It might be worth reasoning about what the best way to do this would be.

You've already mentioned one. But there might be a better way to inform a user that they need to change their input to conform to guidelines.

**Comment by ls42** [comment]
I'm no designer myself, so here are a couple of examples from other frameworks:

* [Semantic-UI](http://semantic-ui.com/behaviors/form.html) - Changes background and label color; Adds either a list of messages below the form or some pop up input field captions
* [Boostrap](http://getbootstrap.com/css/#forms-control-validation) - Label and input field outline color changes with optional icons
* [Material Design](http://www.google.com/design/spec/patterns/errors.html#errors-user-input-errors) - Has a very slim approach; Changing the color of the input field (which is basically a line) and adds a text under the input
