### ISSUE TITLE
Frame & Navigation

### ISSUE THREAD

**Issue by iCristiano** [kumailht/flakes#38]
Hi there,
I'm sorry about my probably silly question...

On the navigation example you have a menu with 'li' list link items in a 'div' .view-wrap to the main content, right? My question is: How to hide the content not selected? Is there some specific id or class to use in each content tab to interact with some jquery and show just the selected content and hide others?

Thanks!

**Comment by kumailht** [comment]
@iCristiano Can you post the code excerpt you are referring to? I am having trouble finding it myself.

**Comment by iCristiano** [comment]
http://getflakes.com/preview/frame-and-navigation.html

**Comment by kumailht** [comment]
Alright, I think I see what you're trying to ask.

You want to know if the .view-wrap div gets replaced based on the navigation change, correct?
The answer is that is doesn't. There is no AJAX based show/hide happening.

Every click on the navigation takes you to a different page on your website.

Hope that answers your question, if not, I can clarify.

**Comment by iCristiano** [comment]
Ah ok, no problem.
