### ISSUE TITLE
Bower : ENOGIT git is not installed or not in the PATH error.

### ISSUE THREAD

**Issue by axnpro888** [kumailht/flakes#39]
Sorry to open a new issue. But this is not exactly an issue.

I have downloaded the package and installed bower.
Now, i am trying to install the dependencies using command : Bower install bower.json
I am getting  Bower : ENOGIT git is not installed or not in the PATH error.

Is that necessary to install GIt before using it. ?? What if i dont want to install git
Or i am using the wrong way to install dependencies.
Can anyone please write down the steps to do it. ?

**Comment by billytrend** [comment]
yeah you need git installed and in your path (should be in your path if it is installed)
