### ISSUE TITLE
Horizontal scrollbar / menu toggle bad behaviour

### ISSUE THREAD

**Issue by tagliala** [kumailht/flakes#4]
How to reproduce:

1) Go to http://getflakes.com/preview/index.html
2) resize the window until the menu collapse
3) Click on the navbar toggle
4) expand the window

Tested on both firefox 33 / chrome 39 windows 7 x64

![image](https://cloud.githubusercontent.com/assets/556268/5303012/ebfa7d2c-7be5-11e4-91a1-5a565dff1ce6.png)

![image](https://cloud.githubusercontent.com/assets/556268/5303016/01046714-7be6-11e4-9504-50967b9a5398.png)

**Comment by bslobodin** [comment]
Any progress on finding the fix for this?

**Comment by kumailht** [comment]
There have been a few pull requests made that fix similar things, so I am not sure if the issue remains. It would be nice if someone could reconfirm that the problem exists.

If it does, I am happy to accept a pull request fixing it.

**Comment by tagliala** [comment]
There is a different issue now:

![image](https://cloud.githubusercontent.com/assets/556268/14263046/cdcd4ea8-fab8-11e5-9e4c-c094f13bcdd5.png)
