### ISSUE TITLE
Modal CSS

### ISSUE THREAD

**Issue by vu-dang** [kumailht/flakes#40]
please recommend a modal window CSS that fits with the Flakes theme.    Should I add shadows and rounded corners?   Thanks.

**Comment by kumaildbz** [comment]
My recommendation would be not to use a Modal window at all. There are many ways to solve the same problem that does not involve Modals. Here are two articles that might help:

Design patterns for replacing modal windows
https://developer.appway.com/screen/ShowSingleRecipe/selectedRecipeId/1390246496349

Issues with modal overlays on the web
http://www.jankoatwarpspeed.com/issues-with-modal-overlays-on-the-web/

**Comment by kumailht** [comment]
My recommendation would be not to use a Modal window at all. There are many ways to solve the same problem that does not involve Modals. Here are two articles that might help:

Design patterns for replacing modal windows
https://developer.appway.com/screen/ShowSingleRecipe/selectedRecipeId/1390246496349

Issues with modal overlays on the web
http://www.jankoatwarpspeed.com/issues-with-modal-overlays-on-the-web/
