### ISSUE TITLE
Is Flakes still being maintained? 

### ISSUE THREAD

**Issue by codegaze** [kumailht/flakes#41]
Hello Kumail,

I want to try Flakes for the first time and I was wondering if you 're still maintaining Flakes or is this project 'dead'?
I just want to know its future.

Thank you in advance. :)

**Comment by kumailht** [comment]
@codegaze Absolutely. Don't let the open issues list scare you. All of them are non-critical and more improvements than bugs.

**Comment by codegaze** [comment]
Thank you very much for your answer @kumailht.
Are you going to make any change to the project soon?

I 'm going to use Flakes for a project and I going to come back with comments/recommendations. :)

**Comment by kumailht** [comment]
Changes happen as a bug is found or an improvement is made. There isn't necessarily a schedule to it. Thank you for using Flakes and look forward to your feedback!
