### ISSUE TITLE
Height Issue if content larger than "device" height

### ISSUE THREAD

**Issue by codegaze** [kumailht/flakes#44]
Hi @kumailht 

I think there is an issue with the calculated height if the content is taller than the window or device (etc IPAD) if you have a background color in the page. 

Do you think a solution might be a recalculation on resize (when the user stops resizing of course)?

**Comment by kumailht** [comment]
@codegaze Sorry, I didn't understand the question. The calculated height of which element is not responding to the window resize?

**Comment by codegaze** [comment]
I 'm sorry you are absolutely right.

In the equalizeHeights  function in the base.js you give the .flakes-content and .flakes-navigation a specific height on DOM ready.

If you reduce the height (e.g. portrait/landscape) you have a height problem because the content exceeds the height.

I noticed this because I have a background color in the body of the page.

**Comment by kumailht** [comment]
I'm trying to replicate it here without much luck. Can you post a picture of the problem?

**Comment by codegaze** [comment]
I was getting ready to send you a screenshot when I figured the problem.
This happens when I have ajax data in my table which results to smaller content height (no data from the database yet) when the equilizeHeights is being executed. :)

**Comment by kumailht** [comment]
Aha. Glad it worked out.
